DengueSite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
   url(r'^get_data/',include('get_data.urls')),
   url(r'^admin/', admin.site.urls),
]

get_data/urls.py
from django.conf.urls import url

from . import views


app_name='get_data'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

get_data/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

get_data/views.py
#codeing=utf-8
from django.shortcuts import render
from django.db import connection
from datetime import date

# Create your views here.
def index(request):
	context=dict()
	if 'longitude' in request.POST and 'latitude' in request.POST:
		longitude=float(request.POST['longitude'])
		latitude=float(request.POST['latitude'])
		cursor=connection.cursor()
		sql="SELECT date,zone1,zone2,road,longitude,latitude,\
 ST_Distance(\
 ST_GeogFromText(ST_AsText(ST_MakePoint(longitude,latitude)))\
 ,ST_GeogFromText(ST_AsText(ST_MakePoint(%s,%s)))\
 )as length\
 from denguedata\
 WHERE \
 ST_Distance(\
 ST_GeogFromText(ST_AsText(ST_MakePoint(longitude,latitude)))\
 ,ST_GeogFromText(ST_AsText(ST_MakePoint(%s,%s)))\
 )<=200;"
		cursor.execute(sql,(longitude,latitude,longitude,latitude,))
		data=cursor.fetchall()
		Data=list()
		tmp=dict()
		for eachData in data:
			tmp['date'],tmp['zone1'],tmp['zone2'],tmp['road'],tmp['longitude'],tmp['latitude'],tmp['length']=eachData
			tmp['date']=tmp['date'].__str__()
			Data.append(tmp.copy())
		context['Data']=Data
	return render(request,'get_data/index.html',context)

get_data/templates/get_data/index.html
<h1>輸入經緯度</h1>


<form action="{% url 'get_data:index' %}" method="POST">
{% csrf_token %}
<label>longitude:</label><input type="text" name="longitude"><br>
<label>latitude:</label><input type="text" name="latitude"><br>
<input type="submit" value="submit">
</form>

{% if Data %}
<h3>日期,區,里,路,緯度,經度,距離</h3>
<ul>
{% for data in Data%}
	<li>{{data.date}},{{data.zone1}},{{data.zone2}},{{data.road}},{{data.longitude}},{{data.latitude}},{{data.length}}</li>
{% endfor %}
</ul>
{% endif %}